"""entries table

Revision ID: 383b73d465db
Revises: 7e22ef7899cc
Create Date: 2021-05-15 09:56:53.504646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383b73d465db'
down_revision = '7e22ef7899cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'is_active')
    # ### end Alembic commands ###
