"""entries table

Revision ID: 3dccc76dab0f
Revises: f8bdd1a703cd
Create Date: 2021-05-19 15:04:22.765254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dccc76dab0f'
down_revision = 'f8bdd1a703cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handover',
    sa.Column('ho_id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.String(length=64), nullable=False),
    sa.Column('ticket_type', sa.String(length=64), nullable=False),
    sa.Column('servers', sa.String(length=300), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('steps', sa.String(length=300), nullable=False),
    sa.Column('next_steps', sa.String(length=300), nullable=False),
    sa.Column('chat_url', sa.String(length=300), nullable=False),
    sa.Column('owner', sa.String(length=300), nullable=False),
    sa.Column('old_owners', sa.String(length=300), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('ho_id')
    )
    op.create_index(op.f('ix_handover_chat_url'), 'handover', ['chat_url'], unique=False)
    op.create_index(op.f('ix_handover_next_steps'), 'handover', ['next_steps'], unique=False)
    op.create_index(op.f('ix_handover_old_owners'), 'handover', ['old_owners'], unique=False)
    op.create_index(op.f('ix_handover_owner'), 'handover', ['owner'], unique=False)
    op.create_index(op.f('ix_handover_platform'), 'handover', ['platform'], unique=False)
    op.create_index(op.f('ix_handover_servers'), 'handover', ['servers'], unique=False)
    op.create_index(op.f('ix_handover_state'), 'handover', ['state'], unique=False)
    op.create_index(op.f('ix_handover_steps'), 'handover', ['steps'], unique=False)
    op.create_index(op.f('ix_handover_ticket'), 'handover', ['ticket'], unique=False)
    op.create_index(op.f('ix_handover_ticket_type'), 'handover', ['ticket_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_handover_ticket_type'), table_name='handover')
    op.drop_index(op.f('ix_handover_ticket'), table_name='handover')
    op.drop_index(op.f('ix_handover_steps'), table_name='handover')
    op.drop_index(op.f('ix_handover_state'), table_name='handover')
    op.drop_index(op.f('ix_handover_servers'), table_name='handover')
    op.drop_index(op.f('ix_handover_platform'), table_name='handover')
    op.drop_index(op.f('ix_handover_owner'), table_name='handover')
    op.drop_index(op.f('ix_handover_old_owners'), table_name='handover')
    op.drop_index(op.f('ix_handover_next_steps'), table_name='handover')
    op.drop_index(op.f('ix_handover_chat_url'), table_name='handover')
    op.drop_table('handover')
    # ### end Alembic commands ###
