"""entries table

Revision ID: 3f58583693cc
Revises: 3dccc76dab0f
Create Date: 2021-05-19 16:59:10.869966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f58583693cc'
down_revision = '3dccc76dab0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('chat_url', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_chat_chat_url'), 'chat', ['chat_url'], unique=False)
    op.create_index(op.f('ix_chat_name'), 'chat', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_name'), table_name='chat')
    op.drop_index(op.f('ix_chat_chat_url'), table_name='chat')
    op.drop_table('chat')
    # ### end Alembic commands ###
