"""entries table

Revision ID: 4656b52124d3
Revises: 383b73d465db
Create Date: 2021-05-15 11:36:43.999936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4656b52124d3'
down_revision = '383b73d465db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=False)
    op.create_table('platform',
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('platform_id')
    )
    op.create_index(op.f('ix_platform_name'), 'platform', ['name'], unique=False)
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=False)
    op.create_table('shift',
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('start_hour', sa.Integer(), nullable=True),
    sa.Column('end_hour', sa.Integer(), nullable=True),
    sa.Column('sunday', sa.Boolean(), nullable=True),
    sa.Column('monday', sa.Boolean(), nullable=True),
    sa.Column('tuesday', sa.Boolean(), nullable=True),
    sa.Column('wednesday', sa.Boolean(), nullable=True),
    sa.Column('thursday', sa.Boolean(), nullable=True),
    sa.Column('friday', sa.Boolean(), nullable=True),
    sa.Column('saturday', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_index(op.f('ix_shift_name'), 'shift', ['name'], unique=False)
    op.add_column('person', sa.Column('group', sa.Integer(), nullable=True))
    op.add_column('person', sa.Column('platform', sa.Integer(), nullable=True))
    op.add_column('person', sa.Column('role', sa.Integer(), nullable=True))
    op.add_column('person', sa.Column('shift', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'shift')
    op.drop_column('person', 'role')
    op.drop_column('person', 'platform')
    op.drop_column('person', 'group')
    op.drop_index(op.f('ix_shift_name'), table_name='shift')
    op.drop_table('shift')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_platform_name'), table_name='platform')
    op.drop_table('platform')
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
