"""entries table

Revision ID: 7e22ef7899cc
Revises: 
Create Date: 2021-05-15 09:37:03.114867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e22ef7899cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=64), nullable=False),
    sa.Column('lname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_index(op.f('ix_person_email'), 'person', ['email'], unique=False)
    op.create_index(op.f('ix_person_fname'), 'person', ['fname'], unique=False)
    op.create_index(op.f('ix_person_lname'), 'person', ['lname'], unique=False)
    op.create_index(op.f('ix_person_username'), 'person', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_username'), table_name='person')
    op.drop_index(op.f('ix_person_lname'), table_name='person')
    op.drop_index(op.f('ix_person_fname'), table_name='person')
    op.drop_index(op.f('ix_person_email'), table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###
