"""entries table

Revision ID: f70ce2a6bb66
Revises: 3f58583693cc
Create Date: 2021-05-20 13:06:07.578960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f70ce2a6bb66'
down_revision = '3f58583693cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handover', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index('ix_handover_state', table_name='handover')
    op.drop_column('handover', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handover', sa.Column('state', mysql.VARCHAR(length=64), nullable=False))
    op.create_index('ix_handover_state', 'handover', ['state'], unique=False)
    op.drop_column('handover', 'is_active')
    # ### end Alembic commands ###
