"""entries table

Revision ID: f8bdd1a703cd
Revises: 4656b52124d3
Create Date: 2021-05-15 21:58:31.627298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8bdd1a703cd'
down_revision = '4656b52124d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift',
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('start_hour', sa.String(length=64), nullable=True),
    sa.Column('end_hour', sa.String(length=64), nullable=True),
    sa.Column('sunday', sa.Boolean(), nullable=True),
    sa.Column('monday', sa.Boolean(), nullable=True),
    sa.Column('tuesday', sa.Boolean(), nullable=True),
    sa.Column('wednesday', sa.Boolean(), nullable=True),
    sa.Column('thursday', sa.Boolean(), nullable=True),
    sa.Column('friday', sa.Boolean(), nullable=True),
    sa.Column('saturday', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_index(op.f('ix_shift_name'), 'shift', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_name'), table_name='shift')
    op.drop_table('shift')
    # ### end Alembic commands ###
